version: '3.4'

services:
  db:
    image: postgres
    ports: 
    - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: transferer 
      POSTGRES_USER: transferer 
      POSTGRES_DB: transferer
    networks:
      - transferer-network
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  api:
    image: ${DOCKER_REGISTRY-}api
    ports:
    - 44300:443
    - 8080:80
    build:
      context: .
      dockerfile: Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80; #https://+:443;
    depends_on: 
      - db
    networks:
      - transferer-network
    volumes:
      - storage-volume:/app/Storage

networks:
  transferer-network:
    driver: bridge

volumes:
  postgres-volume:
  storage-volume: